### ISSUE TITLE
Jupyter notebook error

### ISSUE THREAD

**Issue by jtlz2** [alexmojaki/sorcery#14]
Hi @alexmojaki love sorcery - thank you!

Just been trying to invoke dict_of inside Jupyter but get the below - any ideas? Thanks again!

```python
from sorcery import dict_of
my_dict=dict_of(x,y,z)
```

```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)

[...]

.../lib/python3.9/site-packages/sorcery/core.py in __call__(self, *args, **kwargs)
    183 
    184         executing = Source.executing(frame)
--> 185         assert executing.node, "Failed to find call node"
    186         return self.at(FrameInfo(executing))(*args, **kwargs)
    187 

AssertionError: Failed to find call node
```

**Comment by alexmojaki** [comment]
Probably https://github.com/alexmojaki/executing/issues/58. What's your version of `executing`?

**Comment by hwalinga** [comment]
I can reproduce this on a Python REPL. But IPython works fine. The issue 58 is indeed fixed.

```
» python                       
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>  import sorcery
  File "<stdin>", line 1
    import sorcery
IndentationError: unexpected indent
>>> import sorcery
>>> import sys
>>> from executing import Source, __version__
>>> def get_node():
...     frame = sys._getframe(1)
...     return Source.executing(frame).node
... 
>>> node = get_node()
>>> print(node)
None
>>> import sorcery
>>> x, y, z = 1, 2, 3
>>> sorcery.from_dict(x, y, z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sorcery' has no attribute 'from_dict'
>>> sorcery.dict_of(x, y, z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hielke/.local/lib/python3.9/site-packages/sorcery/core.py", line 185, in __call__
    assert executing.node, "Failed to find call node"
AssertionError: Failed to find call node
>>> sorcery.__version__
'0.2.2'
>>> import executing
>>> executing.__version__
'1.1.1'
```

**Comment by alexmojaki** [comment]
That's normal, source code isn't available in the normal REPL.
