### ISSUE TITLE
dict_of doesn't work in the python shell

### ISSUE THREAD

**Issue by d1618033** [alexmojaki/sorcery#5]
```
$ python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x = 1
>>> y = 2
>>> from sorcery import dict_of
>>> dict_of(x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/PycharmProjects/sandbox/venv/lib/python3.6/site-packages/sorcery/core.py", line 177, in __call__
    while frame.f_code in self._excluded_codes or frame.f_code.co_filename.startswith('<'):
AttributeError: 'NoneType' object has no attribute 'f_code'
```

**Comment by alexmojaki** [comment]
None of this is going to work in a regular shell, access to the source code is required. I should probably add a note to the README about it.

It should work in an IPython notebook or shell though.
