### ISSUE TITLE
dict_of strange behavior

### ISSUE THREAD

**Issue by DavidMertz** [alexmojaki/sorcery#6]
```python
% ipython
Python 3.8.2 | packaged by conda-forge | (default, Apr 16 2020, 18:04:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %doctest_mode
Exception reporting mode: Plain
Doctest mode is: ON
>>> import sorcery
>>> sorcery.__version__
'0.2.0'
>>> x, y, z = range(3)
>>> sorcery.dict_of(x, y, z)
{'code_obj': 0, 'user_global_ns': 1, 'user_ns': 2}
>>> sorcery.dict_of(x, y, z, w='WTF?')
{'code_obj': 0, 'user_global_ns': 1, 'user_ns': 2, 'w': 'WTF?'}
>>> dict(x=x, y=y, z=z)
{'x': 0, 'y': 1, 'z': 2}
```

**Comment by alexmojaki** [comment]
Haha that's why you need syntactic support for this feature instead of magic functions that analyse bytecode and source code. Magic doesn't mix well with magic.

This is very interesting though. Does it only happen with doctest_mode?

**Comment by DavidMertz** [comment]
The bug has nothing to do with doctest_mode. I just switched that on to make the display simpler.  That mode just changes the interactive prompts, nothing deep.

**Comment by DavidMertz** [comment]
Surprisingly, we get a different wrong behavior in the the plain shell:

```python
% python
Python 3.8.2 | packaged by conda-forge | (default, Apr 16 2020, 18:04:51)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sorcery
>>> x, y, z = range(3)
>>> sorcery.dict_of(x, y, z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dmertz/miniconda3/envs/play/lib/python3.8/site-packages/sorcery/core.py", line 177, in __call__
    while frame.f_code in self._excluded_codes or frame.f_code.co_filename.startswith('<'):
AttributeError: 'NoneType' object has no attribute 'f_code'
```

**Comment by alexmojaki** [comment]
> Surprisingly, we get a different wrong behavior in the the plain shell:

That's expected https://github.com/alexmojaki/sorcery/issues/5

**Comment by DavidMertz** [comment]
And something yet differently wrong again if I run a script!

```python
% python ~/tmp/sorcery.py
Traceback (most recent call last):
  File "/home/dmertz/tmp/sorcery.py", line 1, in <module>
    import sorcery
  File "/home/dmertz/tmp/sorcery.py", line 3, in <module>
    print(sorcery.dict_of(x, y, z))
AttributeError: partially initialized module 'sorcery' has no attribute 'dict_of' (most likely due to a circular import)
```

```bash
(play) 694-cleaning-data [master|●2✚ 1]
% cat ~/tmp/sorcery.py
import sorcery
x, y, z = range(3)
print(sorcery.dict_of(x, y, z))
```

**Comment by alexmojaki** [comment]
Haha you had me worried for a second there. That's just because your file is named sorcery.

**Comment by DavidMertz** [comment]
Oh... yeah.  That's fine then:

```bash
% mv ~/tmp/sorcery.py ~/tmp/sorcery-test.py
(play) 697-cleaning-data [master|●2✚ 1]
% python ~/tmp/sorcery-test.py
{'x': 0, 'y': 1, 'z': 2}
```

**Comment by alexmojaki** [comment]
Thanks for bringing this to my attention! The problem in sorcery was pretty simple, it was looking at the wrong frame. But while investigating it I also found problems in the underlying library which are fixed here: https://github.com/alexmojaki/executing/commit/e09d9279edd8390cde3fe4d313fa72e8ba322fc6

`pip install -U sorcery executing` to try again.

Support for IPython will always be shaky, it's more complicated to do and I haven't made any automated tests for 'run this in an IPython shell'.

**Comment by DavidMertz** [comment]
Still broken.

```python
% ipython
Python 3.8.2 | packaged by conda-forge | (default, Apr 16 2020, 18:04:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sorcery

In [2]: sorcery.__version__
Out[2]: '0.2.1'

In [3]: x, y, z = range(3)

In [4]: sorcery.dict_of(x, y, z)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-d7ec38415fe8> in <module>
----> 1 sorcery.dict_of(x, y, z)

~/miniconda3/envs/play/lib/python3.8/site-packages/sorcery/core.py in __call__(self, *args, **kwargs)
    179
    180         executing = Source.executing(frame)
--> 181         assert executing.node, "Failed to find call node"
    182         return self.at(FrameInfo(executing))(*args, **kwargs)
    183

AssertionError: Failed to find call node
```

**Comment by alexmojaki** [comment]
Check `executing.__version__`. Did you upgrade it?

**Comment by DavidMertz** [comment]
Umm... that's in the code above already.  0.2.1.

**Comment by DavidMertz** [comment]
It fails in a different way in 0.2.1 than it did in 0.2.0.  As shown in the several copies of text from the shell.

**Comment by alexmojaki** [comment]
You upgraded sorcery, I said you need to upgrade both sorcery and executing. Both of them needed fixes for this case. executing is the lower level library that powers sorcery.

**Comment by DavidMertz** [comment]
Oh... I never explicitly installed executing. I'll try that later.

**Comment by DavidMertz** [comment]
Ok... the error moves around:

```
% pip install -U sorcery executing
Requirement already up-to-date: sorcery in /mnt/sda1/miniconda3-dmertz/envs/play/lib/python3.8/site-packages (0.2.1)
Collecting executing
  Downloading executing-0.4.3.tar.gz (10 kB)
Requirement already satisfied, skipping upgrade: littleutils>=0.2.1 in /mnt/sda1/miniconda3-dmertz/envs/play/lib/python3.8/site-packages (from sorcery) (0.2.2)
Requirement already satisfied, skipping upgrade: wrapt in /mnt/sda1/miniconda3-dmertz/envs/play/lib/python3.8/site-packages (from sorcery) (1.12.1)
Requirement already satisfied, skipping upgrade: asttokens in /mnt/sda1/miniconda3-dmertz/envs/play/lib/python3.8/site-packages (from sorcery) (2.0.4)
Requirement already satisfied, skipping upgrade: six in /mnt/sda1/miniconda3-dmertz/envs/play/lib/python3.8/site-packages (from asttokens->sorcery) (1.14.0)
Building wheels for collected packages: executing
  Building wheel for executing (setup.py) ... done
  Created wheel for executing: filename=executing-0.4.3-py3-none-any.whl size=8458 sha256=51f5ddb5bdb084648859e7dfa0349d43b5926aee68461ed208b30bd108387552
  Stored in directory: /home/dmertz/.cache/pip/wheels/42/a6/3d/34f1f1a44f28649eacd579b71db9f214065c5ec9a0bccf7dfe
Successfully built executing
Installing collected packages: executing
  Attempting uninstall: executing
    Found existing installation: executing 0.4.2
    Uninstalling executing-0.4.2:
      Successfully uninstalled executing-0.4.2
Successfully installed executing-0.4.3
(play) 709-cleaning-data [master|●2✚ 2]
% ipython
Python 3.8.2 | packaged by conda-forge | (default, Apr 16 2020, 18:04:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sorcery import *

In [2]: x, y, z = range(3)

In [3]: dict_of(x, y, z)
Out[3]: {'x': 0, 'y': 1, 'z': 2}

In [4]:
Do you really want to exit ([y]/n)? y
(play) 710-cleaning-data [master|●2✚ 2]
% python
Python 3.8.2 | packaged by conda-forge | (default, Apr 16 2020, 18:04:51)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sorcery import *
>>> x, y, z = range(3)
>>> dict_of(x, y, z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dmertz/miniconda3/envs/play/lib/python3.8/site-packages/sorcery/core.py", line 181, in __call__
    assert executing.node, "Failed to find call node"
AssertionError: Failed to find call node
>>> import executing
>>> executing.__version__
'0.4.3'
```

**Comment by alexmojaki** [comment]
That's still just #5, that's never going to change unless Python makes the source available in the shell. It just so happens that the error message is a bit better now. IPython is fixed.
